import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import SmootherProvider from "@/components/smooth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({
  subsets: ['latin'],
  variable: '--font-inter-tight'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable}`}>
        {/* <SmootherProvider /> */}
        {children}
      </body>
    </html>
  );
}
