
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model SOCK_USERS
 * 
 */
export type SOCK_USERS = Prisma.SOCK_USERSModel
/**
 * Model SOCK_ROOMS
 * 
 */
export type SOCK_ROOMS = Prisma.SOCK_ROOMSModel
/**
 * Model SOCK_PAYLOAD
 * 
 */
export type SOCK_PAYLOAD = Prisma.SOCK_PAYLOADModel
