
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Sock_user` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Sock_user
 * 
 */
export type Sock_userModel = runtime.Types.Result.DefaultSelection<Prisma.$Sock_userPayload>

export type AggregateSock_user = {
  _count: Sock_userCountAggregateOutputType | null
  _avg: Sock_userAvgAggregateOutputType | null
  _sum: Sock_userSumAggregateOutputType | null
  _min: Sock_userMinAggregateOutputType | null
  _max: Sock_userMaxAggregateOutputType | null
}

export type Sock_userAvgAggregateOutputType = {
  id: number | null
  rooms: number | null
  connects: number | null
}

export type Sock_userSumAggregateOutputType = {
  id: number | null
  rooms: number[]
  connects: number[]
}

export type Sock_userMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  password: string | null
  token: string | null
}

export type Sock_userMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  password: string | null
  token: string | null
}

export type Sock_userCountAggregateOutputType = {
  id: number
  name: number
  email: number
  password: number
  token: number
  rooms: number
  connects: number
  _all: number
}


export type Sock_userAvgAggregateInputType = {
  id?: true
  rooms?: true
  connects?: true
}

export type Sock_userSumAggregateInputType = {
  id?: true
  rooms?: true
  connects?: true
}

export type Sock_userMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
}

export type Sock_userMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
}

export type Sock_userCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
  rooms?: true
  connects?: true
  _all?: true
}

export type Sock_userAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sock_user to aggregate.
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sock_users to fetch.
   */
  orderBy?: Prisma.Sock_userOrderByWithRelationInput | Prisma.Sock_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Sock_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sock_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sock_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sock_users
  **/
  _count?: true | Sock_userCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Sock_userAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Sock_userSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Sock_userMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Sock_userMaxAggregateInputType
}

export type GetSock_userAggregateType<T extends Sock_userAggregateArgs> = {
      [P in keyof T & keyof AggregateSock_user]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSock_user[P]>
    : Prisma.GetScalarType<T[P], AggregateSock_user[P]>
}




export type Sock_userGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Sock_userWhereInput
  orderBy?: Prisma.Sock_userOrderByWithAggregationInput | Prisma.Sock_userOrderByWithAggregationInput[]
  by: Prisma.Sock_userScalarFieldEnum[] | Prisma.Sock_userScalarFieldEnum
  having?: Prisma.Sock_userScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Sock_userCountAggregateInputType | true
  _avg?: Sock_userAvgAggregateInputType
  _sum?: Sock_userSumAggregateInputType
  _min?: Sock_userMinAggregateInputType
  _max?: Sock_userMaxAggregateInputType
}

export type Sock_userGroupByOutputType = {
  id: number
  name: string
  email: string
  password: string
  token: string
  rooms: number[]
  connects: number[]
  _count: Sock_userCountAggregateOutputType | null
  _avg: Sock_userAvgAggregateOutputType | null
  _sum: Sock_userSumAggregateOutputType | null
  _min: Sock_userMinAggregateOutputType | null
  _max: Sock_userMaxAggregateOutputType | null
}

type GetSock_userGroupByPayload<T extends Sock_userGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Sock_userGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Sock_userGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Sock_userGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Sock_userGroupByOutputType[P]>
      }
    >
  >



export type Sock_userWhereInput = {
  AND?: Prisma.Sock_userWhereInput | Prisma.Sock_userWhereInput[]
  OR?: Prisma.Sock_userWhereInput[]
  NOT?: Prisma.Sock_userWhereInput | Prisma.Sock_userWhereInput[]
  id?: Prisma.IntFilter<"Sock_user"> | number
  name?: Prisma.StringFilter<"Sock_user"> | string
  email?: Prisma.StringFilter<"Sock_user"> | string
  password?: Prisma.StringFilter<"Sock_user"> | string
  token?: Prisma.StringFilter<"Sock_user"> | string
  rooms?: Prisma.IntNullableListFilter<"Sock_user">
  connects?: Prisma.IntNullableListFilter<"Sock_user">
}

export type Sock_userOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  connects?: Prisma.SortOrder
}

export type Sock_userWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.Sock_userWhereInput | Prisma.Sock_userWhereInput[]
  OR?: Prisma.Sock_userWhereInput[]
  NOT?: Prisma.Sock_userWhereInput | Prisma.Sock_userWhereInput[]
  name?: Prisma.StringFilter<"Sock_user"> | string
  password?: Prisma.StringFilter<"Sock_user"> | string
  token?: Prisma.StringFilter<"Sock_user"> | string
  rooms?: Prisma.IntNullableListFilter<"Sock_user">
  connects?: Prisma.IntNullableListFilter<"Sock_user">
}, "id" | "email">

export type Sock_userOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  connects?: Prisma.SortOrder
  _count?: Prisma.Sock_userCountOrderByAggregateInput
  _avg?: Prisma.Sock_userAvgOrderByAggregateInput
  _max?: Prisma.Sock_userMaxOrderByAggregateInput
  _min?: Prisma.Sock_userMinOrderByAggregateInput
  _sum?: Prisma.Sock_userSumOrderByAggregateInput
}

export type Sock_userScalarWhereWithAggregatesInput = {
  AND?: Prisma.Sock_userScalarWhereWithAggregatesInput | Prisma.Sock_userScalarWhereWithAggregatesInput[]
  OR?: Prisma.Sock_userScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Sock_userScalarWhereWithAggregatesInput | Prisma.Sock_userScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Sock_user"> | number
  name?: Prisma.StringWithAggregatesFilter<"Sock_user"> | string
  email?: Prisma.StringWithAggregatesFilter<"Sock_user"> | string
  password?: Prisma.StringWithAggregatesFilter<"Sock_user"> | string
  token?: Prisma.StringWithAggregatesFilter<"Sock_user"> | string
  rooms?: Prisma.IntNullableListFilter<"Sock_user">
  connects?: Prisma.IntNullableListFilter<"Sock_user">
}

export type Sock_userCreateInput = {
  name: string
  email: string
  password: string
  token: string
  rooms?: Prisma.Sock_userCreateroomsInput | number[]
  connects?: Prisma.Sock_userCreateconnectsInput | number[]
}

export type Sock_userUncheckedCreateInput = {
  id?: number
  name: string
  email: string
  password: string
  token: string
  rooms?: Prisma.Sock_userCreateroomsInput | number[]
  connects?: Prisma.Sock_userCreateconnectsInput | number[]
}

export type Sock_userUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.Sock_userUpdateroomsInput | number[]
  connects?: Prisma.Sock_userUpdateconnectsInput | number[]
}

export type Sock_userUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.Sock_userUpdateroomsInput | number[]
  connects?: Prisma.Sock_userUpdateconnectsInput | number[]
}

export type Sock_userCreateManyInput = {
  id?: number
  name: string
  email: string
  password: string
  token: string
  rooms?: Prisma.Sock_userCreateroomsInput | number[]
  connects?: Prisma.Sock_userCreateconnectsInput | number[]
}

export type Sock_userUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.Sock_userUpdateroomsInput | number[]
  connects?: Prisma.Sock_userUpdateconnectsInput | number[]
}

export type Sock_userUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.Sock_userUpdateroomsInput | number[]
  connects?: Prisma.Sock_userUpdateconnectsInput | number[]
}

export type IntNullableListFilter<$PrismaModel = never> = {
  equals?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  has?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  hasEvery?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  hasSome?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type Sock_userCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  connects?: Prisma.SortOrder
}

export type Sock_userAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  connects?: Prisma.SortOrder
}

export type Sock_userMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type Sock_userMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type Sock_userSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  connects?: Prisma.SortOrder
}

export type Sock_userCreateroomsInput = {
  set: number[]
}

export type Sock_userCreateconnectsInput = {
  set: number[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type Sock_userUpdateroomsInput = {
  set?: number[]
  push?: number | number[]
}

export type Sock_userUpdateconnectsInput = {
  set?: number[]
  push?: number | number[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type Sock_userSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  connects?: boolean
}, ExtArgs["result"]["sock_user"]>

export type Sock_userSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  connects?: boolean
}, ExtArgs["result"]["sock_user"]>

export type Sock_userSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  connects?: boolean
}, ExtArgs["result"]["sock_user"]>

export type Sock_userSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  connects?: boolean
}

export type Sock_userOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "password" | "token" | "rooms" | "connects", ExtArgs["result"]["sock_user"]>

export type $Sock_userPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Sock_user"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    email: string
    password: string
    token: string
    rooms: number[]
    connects: number[]
  }, ExtArgs["result"]["sock_user"]>
  composites: {}
}

export type Sock_userGetPayload<S extends boolean | null | undefined | Sock_userDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Sock_userPayload, S>

export type Sock_userCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Sock_userFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Sock_userCountAggregateInputType | true
  }

export interface Sock_userDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Sock_user'], meta: { name: 'Sock_user' } }
  /**
   * Find zero or one Sock_user that matches the filter.
   * @param {Sock_userFindUniqueArgs} args - Arguments to find a Sock_user
   * @example
   * // Get one Sock_user
   * const sock_user = await prisma.sock_user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Sock_userFindUniqueArgs>(args: Prisma.SelectSubset<T, Sock_userFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sock_user that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Sock_userFindUniqueOrThrowArgs} args - Arguments to find a Sock_user
   * @example
   * // Get one Sock_user
   * const sock_user = await prisma.sock_user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Sock_userFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Sock_userFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sock_user that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userFindFirstArgs} args - Arguments to find a Sock_user
   * @example
   * // Get one Sock_user
   * const sock_user = await prisma.sock_user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Sock_userFindFirstArgs>(args?: Prisma.SelectSubset<T, Sock_userFindFirstArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sock_user that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userFindFirstOrThrowArgs} args - Arguments to find a Sock_user
   * @example
   * // Get one Sock_user
   * const sock_user = await prisma.sock_user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Sock_userFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Sock_userFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sock_users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sock_users
   * const sock_users = await prisma.sock_user.findMany()
   * 
   * // Get first 10 Sock_users
   * const sock_users = await prisma.sock_user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sock_userWithIdOnly = await prisma.sock_user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Sock_userFindManyArgs>(args?: Prisma.SelectSubset<T, Sock_userFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sock_user.
   * @param {Sock_userCreateArgs} args - Arguments to create a Sock_user.
   * @example
   * // Create one Sock_user
   * const Sock_user = await prisma.sock_user.create({
   *   data: {
   *     // ... data to create a Sock_user
   *   }
   * })
   * 
   */
  create<T extends Sock_userCreateArgs>(args: Prisma.SelectSubset<T, Sock_userCreateArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sock_users.
   * @param {Sock_userCreateManyArgs} args - Arguments to create many Sock_users.
   * @example
   * // Create many Sock_users
   * const sock_user = await prisma.sock_user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Sock_userCreateManyArgs>(args?: Prisma.SelectSubset<T, Sock_userCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sock_users and returns the data saved in the database.
   * @param {Sock_userCreateManyAndReturnArgs} args - Arguments to create many Sock_users.
   * @example
   * // Create many Sock_users
   * const sock_user = await prisma.sock_user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sock_users and only return the `id`
   * const sock_userWithIdOnly = await prisma.sock_user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Sock_userCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Sock_userCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Sock_user.
   * @param {Sock_userDeleteArgs} args - Arguments to delete one Sock_user.
   * @example
   * // Delete one Sock_user
   * const Sock_user = await prisma.sock_user.delete({
   *   where: {
   *     // ... filter to delete one Sock_user
   *   }
   * })
   * 
   */
  delete<T extends Sock_userDeleteArgs>(args: Prisma.SelectSubset<T, Sock_userDeleteArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sock_user.
   * @param {Sock_userUpdateArgs} args - Arguments to update one Sock_user.
   * @example
   * // Update one Sock_user
   * const sock_user = await prisma.sock_user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Sock_userUpdateArgs>(args: Prisma.SelectSubset<T, Sock_userUpdateArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sock_users.
   * @param {Sock_userDeleteManyArgs} args - Arguments to filter Sock_users to delete.
   * @example
   * // Delete a few Sock_users
   * const { count } = await prisma.sock_user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Sock_userDeleteManyArgs>(args?: Prisma.SelectSubset<T, Sock_userDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sock_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sock_users
   * const sock_user = await prisma.sock_user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Sock_userUpdateManyArgs>(args: Prisma.SelectSubset<T, Sock_userUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sock_users and returns the data updated in the database.
   * @param {Sock_userUpdateManyAndReturnArgs} args - Arguments to update many Sock_users.
   * @example
   * // Update many Sock_users
   * const sock_user = await prisma.sock_user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sock_users and only return the `id`
   * const sock_userWithIdOnly = await prisma.sock_user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Sock_userUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Sock_userUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Sock_user.
   * @param {Sock_userUpsertArgs} args - Arguments to update or create a Sock_user.
   * @example
   * // Update or create a Sock_user
   * const sock_user = await prisma.sock_user.upsert({
   *   create: {
   *     // ... data to create a Sock_user
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sock_user we want to update
   *   }
   * })
   */
  upsert<T extends Sock_userUpsertArgs>(args: Prisma.SelectSubset<T, Sock_userUpsertArgs<ExtArgs>>): Prisma.Prisma__Sock_userClient<runtime.Types.Result.GetResult<Prisma.$Sock_userPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sock_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userCountArgs} args - Arguments to filter Sock_users to count.
   * @example
   * // Count the number of Sock_users
   * const count = await prisma.sock_user.count({
   *   where: {
   *     // ... the filter for the Sock_users we want to count
   *   }
   * })
  **/
  count<T extends Sock_userCountArgs>(
    args?: Prisma.Subset<T, Sock_userCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Sock_userCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sock_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Sock_userAggregateArgs>(args: Prisma.Subset<T, Sock_userAggregateArgs>): Prisma.PrismaPromise<GetSock_userAggregateType<T>>

  /**
   * Group by Sock_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sock_userGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Sock_userGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Sock_userGroupByArgs['orderBy'] }
      : { orderBy?: Sock_userGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Sock_userGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSock_userGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Sock_user model
 */
readonly fields: Sock_userFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Sock_user.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Sock_userClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Sock_user model
 */
export interface Sock_userFieldRefs {
  readonly id: Prisma.FieldRef<"Sock_user", 'Int'>
  readonly name: Prisma.FieldRef<"Sock_user", 'String'>
  readonly email: Prisma.FieldRef<"Sock_user", 'String'>
  readonly password: Prisma.FieldRef<"Sock_user", 'String'>
  readonly token: Prisma.FieldRef<"Sock_user", 'String'>
  readonly rooms: Prisma.FieldRef<"Sock_user", 'Int[]'>
  readonly connects: Prisma.FieldRef<"Sock_user", 'Int[]'>
}
    

// Custom InputTypes
/**
 * Sock_user findUnique
 */
export type Sock_userFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter, which Sock_user to fetch.
   */
  where: Prisma.Sock_userWhereUniqueInput
}

/**
 * Sock_user findUniqueOrThrow
 */
export type Sock_userFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter, which Sock_user to fetch.
   */
  where: Prisma.Sock_userWhereUniqueInput
}

/**
 * Sock_user findFirst
 */
export type Sock_userFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter, which Sock_user to fetch.
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sock_users to fetch.
   */
  orderBy?: Prisma.Sock_userOrderByWithRelationInput | Prisma.Sock_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sock_users.
   */
  cursor?: Prisma.Sock_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sock_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sock_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sock_users.
   */
  distinct?: Prisma.Sock_userScalarFieldEnum | Prisma.Sock_userScalarFieldEnum[]
}

/**
 * Sock_user findFirstOrThrow
 */
export type Sock_userFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter, which Sock_user to fetch.
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sock_users to fetch.
   */
  orderBy?: Prisma.Sock_userOrderByWithRelationInput | Prisma.Sock_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sock_users.
   */
  cursor?: Prisma.Sock_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sock_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sock_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sock_users.
   */
  distinct?: Prisma.Sock_userScalarFieldEnum | Prisma.Sock_userScalarFieldEnum[]
}

/**
 * Sock_user findMany
 */
export type Sock_userFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter, which Sock_users to fetch.
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sock_users to fetch.
   */
  orderBy?: Prisma.Sock_userOrderByWithRelationInput | Prisma.Sock_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sock_users.
   */
  cursor?: Prisma.Sock_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sock_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sock_users.
   */
  skip?: number
  distinct?: Prisma.Sock_userScalarFieldEnum | Prisma.Sock_userScalarFieldEnum[]
}

/**
 * Sock_user create
 */
export type Sock_userCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * The data needed to create a Sock_user.
   */
  data: Prisma.XOR<Prisma.Sock_userCreateInput, Prisma.Sock_userUncheckedCreateInput>
}

/**
 * Sock_user createMany
 */
export type Sock_userCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sock_users.
   */
  data: Prisma.Sock_userCreateManyInput | Prisma.Sock_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sock_user createManyAndReturn
 */
export type Sock_userCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * The data used to create many Sock_users.
   */
  data: Prisma.Sock_userCreateManyInput | Prisma.Sock_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sock_user update
 */
export type Sock_userUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * The data needed to update a Sock_user.
   */
  data: Prisma.XOR<Prisma.Sock_userUpdateInput, Prisma.Sock_userUncheckedUpdateInput>
  /**
   * Choose, which Sock_user to update.
   */
  where: Prisma.Sock_userWhereUniqueInput
}

/**
 * Sock_user updateMany
 */
export type Sock_userUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sock_users.
   */
  data: Prisma.XOR<Prisma.Sock_userUpdateManyMutationInput, Prisma.Sock_userUncheckedUpdateManyInput>
  /**
   * Filter which Sock_users to update
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * Limit how many Sock_users to update.
   */
  limit?: number
}

/**
 * Sock_user updateManyAndReturn
 */
export type Sock_userUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * The data used to update Sock_users.
   */
  data: Prisma.XOR<Prisma.Sock_userUpdateManyMutationInput, Prisma.Sock_userUncheckedUpdateManyInput>
  /**
   * Filter which Sock_users to update
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * Limit how many Sock_users to update.
   */
  limit?: number
}

/**
 * Sock_user upsert
 */
export type Sock_userUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * The filter to search for the Sock_user to update in case it exists.
   */
  where: Prisma.Sock_userWhereUniqueInput
  /**
   * In case the Sock_user found by the `where` argument doesn't exist, create a new Sock_user with this data.
   */
  create: Prisma.XOR<Prisma.Sock_userCreateInput, Prisma.Sock_userUncheckedCreateInput>
  /**
   * In case the Sock_user was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Sock_userUpdateInput, Prisma.Sock_userUncheckedUpdateInput>
}

/**
 * Sock_user delete
 */
export type Sock_userDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
  /**
   * Filter which Sock_user to delete.
   */
  where: Prisma.Sock_userWhereUniqueInput
}

/**
 * Sock_user deleteMany
 */
export type Sock_userDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sock_users to delete
   */
  where?: Prisma.Sock_userWhereInput
  /**
   * Limit how many Sock_users to delete.
   */
  limit?: number
}

/**
 * Sock_user without action
 */
export type Sock_userDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sock_user
   */
  select?: Prisma.Sock_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sock_user
   */
  omit?: Prisma.Sock_userOmit<ExtArgs> | null
}
