
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SOCK_ROOMS` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SOCK_ROOMS
 * 
 */
export type SOCK_ROOMSModel = runtime.Types.Result.DefaultSelection<Prisma.$SOCK_ROOMSPayload>

export type AggregateSOCK_ROOMS = {
  _count: SOCK_ROOMSCountAggregateOutputType | null
  _avg: SOCK_ROOMSAvgAggregateOutputType | null
  _sum: SOCK_ROOMSSumAggregateOutputType | null
  _min: SOCK_ROOMSMinAggregateOutputType | null
  _max: SOCK_ROOMSMaxAggregateOutputType | null
}

export type SOCK_ROOMSAvgAggregateOutputType = {
  id: number | null
  user_one: number | null
  user_two: number | null
}

export type SOCK_ROOMSSumAggregateOutputType = {
  id: number | null
  user_one: number | null
  user_two: number | null
}

export type SOCK_ROOMSMinAggregateOutputType = {
  id: number | null
  user_one: number | null
  user_two: number | null
}

export type SOCK_ROOMSMaxAggregateOutputType = {
  id: number | null
  user_one: number | null
  user_two: number | null
}

export type SOCK_ROOMSCountAggregateOutputType = {
  id: number
  user_one: number
  user_two: number
  _all: number
}


export type SOCK_ROOMSAvgAggregateInputType = {
  id?: true
  user_one?: true
  user_two?: true
}

export type SOCK_ROOMSSumAggregateInputType = {
  id?: true
  user_one?: true
  user_two?: true
}

export type SOCK_ROOMSMinAggregateInputType = {
  id?: true
  user_one?: true
  user_two?: true
}

export type SOCK_ROOMSMaxAggregateInputType = {
  id?: true
  user_one?: true
  user_two?: true
}

export type SOCK_ROOMSCountAggregateInputType = {
  id?: true
  user_one?: true
  user_two?: true
  _all?: true
}

export type SOCK_ROOMSAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_ROOMS to aggregate.
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_ROOMS to fetch.
   */
  orderBy?: Prisma.SOCK_ROOMSOrderByWithRelationInput | Prisma.SOCK_ROOMSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SOCK_ROOMSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_ROOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_ROOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SOCK_ROOMS
  **/
  _count?: true | SOCK_ROOMSCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SOCK_ROOMSAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SOCK_ROOMSSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SOCK_ROOMSMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SOCK_ROOMSMaxAggregateInputType
}

export type GetSOCK_ROOMSAggregateType<T extends SOCK_ROOMSAggregateArgs> = {
      [P in keyof T & keyof AggregateSOCK_ROOMS]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSOCK_ROOMS[P]>
    : Prisma.GetScalarType<T[P], AggregateSOCK_ROOMS[P]>
}




export type SOCK_ROOMSGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SOCK_ROOMSWhereInput
  orderBy?: Prisma.SOCK_ROOMSOrderByWithAggregationInput | Prisma.SOCK_ROOMSOrderByWithAggregationInput[]
  by: Prisma.SOCK_ROOMSScalarFieldEnum[] | Prisma.SOCK_ROOMSScalarFieldEnum
  having?: Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SOCK_ROOMSCountAggregateInputType | true
  _avg?: SOCK_ROOMSAvgAggregateInputType
  _sum?: SOCK_ROOMSSumAggregateInputType
  _min?: SOCK_ROOMSMinAggregateInputType
  _max?: SOCK_ROOMSMaxAggregateInputType
}

export type SOCK_ROOMSGroupByOutputType = {
  id: number
  user_one: number
  user_two: number
  _count: SOCK_ROOMSCountAggregateOutputType | null
  _avg: SOCK_ROOMSAvgAggregateOutputType | null
  _sum: SOCK_ROOMSSumAggregateOutputType | null
  _min: SOCK_ROOMSMinAggregateOutputType | null
  _max: SOCK_ROOMSMaxAggregateOutputType | null
}

type GetSOCK_ROOMSGroupByPayload<T extends SOCK_ROOMSGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SOCK_ROOMSGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SOCK_ROOMSGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SOCK_ROOMSGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SOCK_ROOMSGroupByOutputType[P]>
      }
    >
  >



export type SOCK_ROOMSWhereInput = {
  AND?: Prisma.SOCK_ROOMSWhereInput | Prisma.SOCK_ROOMSWhereInput[]
  OR?: Prisma.SOCK_ROOMSWhereInput[]
  NOT?: Prisma.SOCK_ROOMSWhereInput | Prisma.SOCK_ROOMSWhereInput[]
  id?: Prisma.IntFilter<"SOCK_ROOMS"> | number
  user_one?: Prisma.IntFilter<"SOCK_ROOMS"> | number
  user_two?: Prisma.IntFilter<"SOCK_ROOMS"> | number
}

export type SOCK_ROOMSOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}

export type SOCK_ROOMSWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SOCK_ROOMSWhereInput | Prisma.SOCK_ROOMSWhereInput[]
  OR?: Prisma.SOCK_ROOMSWhereInput[]
  NOT?: Prisma.SOCK_ROOMSWhereInput | Prisma.SOCK_ROOMSWhereInput[]
  user_one?: Prisma.IntFilter<"SOCK_ROOMS"> | number
  user_two?: Prisma.IntFilter<"SOCK_ROOMS"> | number
}, "id">

export type SOCK_ROOMSOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
  _count?: Prisma.SOCK_ROOMSCountOrderByAggregateInput
  _avg?: Prisma.SOCK_ROOMSAvgOrderByAggregateInput
  _max?: Prisma.SOCK_ROOMSMaxOrderByAggregateInput
  _min?: Prisma.SOCK_ROOMSMinOrderByAggregateInput
  _sum?: Prisma.SOCK_ROOMSSumOrderByAggregateInput
}

export type SOCK_ROOMSScalarWhereWithAggregatesInput = {
  AND?: Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput | Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput[]
  OR?: Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput | Prisma.SOCK_ROOMSScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SOCK_ROOMS"> | number
  user_one?: Prisma.IntWithAggregatesFilter<"SOCK_ROOMS"> | number
  user_two?: Prisma.IntWithAggregatesFilter<"SOCK_ROOMS"> | number
}

export type SOCK_ROOMSCreateInput = {
  user_one: number
  user_two: number
}

export type SOCK_ROOMSUncheckedCreateInput = {
  id?: number
  user_one: number
  user_two: number
}

export type SOCK_ROOMSUpdateInput = {
  user_one?: Prisma.IntFieldUpdateOperationsInput | number
  user_two?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SOCK_ROOMSUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_one?: Prisma.IntFieldUpdateOperationsInput | number
  user_two?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SOCK_ROOMSCreateManyInput = {
  id?: number
  user_one: number
  user_two: number
}

export type SOCK_ROOMSUpdateManyMutationInput = {
  user_one?: Prisma.IntFieldUpdateOperationsInput | number
  user_two?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SOCK_ROOMSUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_one?: Prisma.IntFieldUpdateOperationsInput | number
  user_two?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SOCK_ROOMSCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}

export type SOCK_ROOMSAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}

export type SOCK_ROOMSMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}

export type SOCK_ROOMSMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}

export type SOCK_ROOMSSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_one?: Prisma.SortOrder
  user_two?: Prisma.SortOrder
}



export type SOCK_ROOMSSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_one?: boolean
  user_two?: boolean
}, ExtArgs["result"]["sOCK_ROOMS"]>

export type SOCK_ROOMSSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_one?: boolean
  user_two?: boolean
}, ExtArgs["result"]["sOCK_ROOMS"]>

export type SOCK_ROOMSSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_one?: boolean
  user_two?: boolean
}, ExtArgs["result"]["sOCK_ROOMS"]>

export type SOCK_ROOMSSelectScalar = {
  id?: boolean
  user_one?: boolean
  user_two?: boolean
}

export type SOCK_ROOMSOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_one" | "user_two", ExtArgs["result"]["sOCK_ROOMS"]>

export type $SOCK_ROOMSPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SOCK_ROOMS"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_one: number
    user_two: number
  }, ExtArgs["result"]["sOCK_ROOMS"]>
  composites: {}
}

export type SOCK_ROOMSGetPayload<S extends boolean | null | undefined | SOCK_ROOMSDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload, S>

export type SOCK_ROOMSCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SOCK_ROOMSFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SOCK_ROOMSCountAggregateInputType | true
  }

export interface SOCK_ROOMSDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SOCK_ROOMS'], meta: { name: 'SOCK_ROOMS' } }
  /**
   * Find zero or one SOCK_ROOMS that matches the filter.
   * @param {SOCK_ROOMSFindUniqueArgs} args - Arguments to find a SOCK_ROOMS
   * @example
   * // Get one SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SOCK_ROOMSFindUniqueArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SOCK_ROOMS that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SOCK_ROOMSFindUniqueOrThrowArgs} args - Arguments to find a SOCK_ROOMS
   * @example
   * // Get one SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SOCK_ROOMSFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_ROOMS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSFindFirstArgs} args - Arguments to find a SOCK_ROOMS
   * @example
   * // Get one SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SOCK_ROOMSFindFirstArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSFindFirstArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_ROOMS that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSFindFirstOrThrowArgs} args - Arguments to find a SOCK_ROOMS
   * @example
   * // Get one SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SOCK_ROOMSFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SOCK_ROOMS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findMany()
   * 
   * // Get first 10 SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sOCK_ROOMSWithIdOnly = await prisma.sOCK_ROOMS.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SOCK_ROOMSFindManyArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SOCK_ROOMS.
   * @param {SOCK_ROOMSCreateArgs} args - Arguments to create a SOCK_ROOMS.
   * @example
   * // Create one SOCK_ROOMS
   * const SOCK_ROOMS = await prisma.sOCK_ROOMS.create({
   *   data: {
   *     // ... data to create a SOCK_ROOMS
   *   }
   * })
   * 
   */
  create<T extends SOCK_ROOMSCreateArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSCreateArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SOCK_ROOMS.
   * @param {SOCK_ROOMSCreateManyArgs} args - Arguments to create many SOCK_ROOMS.
   * @example
   * // Create many SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SOCK_ROOMSCreateManyArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SOCK_ROOMS and returns the data saved in the database.
   * @param {SOCK_ROOMSCreateManyAndReturnArgs} args - Arguments to create many SOCK_ROOMS.
   * @example
   * // Create many SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SOCK_ROOMS and only return the `id`
   * const sOCK_ROOMSWithIdOnly = await prisma.sOCK_ROOMS.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SOCK_ROOMSCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SOCK_ROOMS.
   * @param {SOCK_ROOMSDeleteArgs} args - Arguments to delete one SOCK_ROOMS.
   * @example
   * // Delete one SOCK_ROOMS
   * const SOCK_ROOMS = await prisma.sOCK_ROOMS.delete({
   *   where: {
   *     // ... filter to delete one SOCK_ROOMS
   *   }
   * })
   * 
   */
  delete<T extends SOCK_ROOMSDeleteArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSDeleteArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SOCK_ROOMS.
   * @param {SOCK_ROOMSUpdateArgs} args - Arguments to update one SOCK_ROOMS.
   * @example
   * // Update one SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SOCK_ROOMSUpdateArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSUpdateArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SOCK_ROOMS.
   * @param {SOCK_ROOMSDeleteManyArgs} args - Arguments to filter SOCK_ROOMS to delete.
   * @example
   * // Delete a few SOCK_ROOMS
   * const { count } = await prisma.sOCK_ROOMS.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SOCK_ROOMSDeleteManyArgs>(args?: Prisma.SelectSubset<T, SOCK_ROOMSDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_ROOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SOCK_ROOMSUpdateManyArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_ROOMS and returns the data updated in the database.
   * @param {SOCK_ROOMSUpdateManyAndReturnArgs} args - Arguments to update many SOCK_ROOMS.
   * @example
   * // Update many SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SOCK_ROOMS and only return the `id`
   * const sOCK_ROOMSWithIdOnly = await prisma.sOCK_ROOMS.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SOCK_ROOMSUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SOCK_ROOMS.
   * @param {SOCK_ROOMSUpsertArgs} args - Arguments to update or create a SOCK_ROOMS.
   * @example
   * // Update or create a SOCK_ROOMS
   * const sOCK_ROOMS = await prisma.sOCK_ROOMS.upsert({
   *   create: {
   *     // ... data to create a SOCK_ROOMS
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SOCK_ROOMS we want to update
   *   }
   * })
   */
  upsert<T extends SOCK_ROOMSUpsertArgs>(args: Prisma.SelectSubset<T, SOCK_ROOMSUpsertArgs<ExtArgs>>): Prisma.Prisma__SOCK_ROOMSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_ROOMSPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SOCK_ROOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSCountArgs} args - Arguments to filter SOCK_ROOMS to count.
   * @example
   * // Count the number of SOCK_ROOMS
   * const count = await prisma.sOCK_ROOMS.count({
   *   where: {
   *     // ... the filter for the SOCK_ROOMS we want to count
   *   }
   * })
  **/
  count<T extends SOCK_ROOMSCountArgs>(
    args?: Prisma.Subset<T, SOCK_ROOMSCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SOCK_ROOMSCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SOCK_ROOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SOCK_ROOMSAggregateArgs>(args: Prisma.Subset<T, SOCK_ROOMSAggregateArgs>): Prisma.PrismaPromise<GetSOCK_ROOMSAggregateType<T>>

  /**
   * Group by SOCK_ROOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_ROOMSGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SOCK_ROOMSGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SOCK_ROOMSGroupByArgs['orderBy'] }
      : { orderBy?: SOCK_ROOMSGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SOCK_ROOMSGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSOCK_ROOMSGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SOCK_ROOMS model
 */
readonly fields: SOCK_ROOMSFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SOCK_ROOMS.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SOCK_ROOMSClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SOCK_ROOMS model
 */
export interface SOCK_ROOMSFieldRefs {
  readonly id: Prisma.FieldRef<"SOCK_ROOMS", 'Int'>
  readonly user_one: Prisma.FieldRef<"SOCK_ROOMS", 'Int'>
  readonly user_two: Prisma.FieldRef<"SOCK_ROOMS", 'Int'>
}
    

// Custom InputTypes
/**
 * SOCK_ROOMS findUnique
 */
export type SOCK_ROOMSFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_ROOMS to fetch.
   */
  where: Prisma.SOCK_ROOMSWhereUniqueInput
}

/**
 * SOCK_ROOMS findUniqueOrThrow
 */
export type SOCK_ROOMSFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_ROOMS to fetch.
   */
  where: Prisma.SOCK_ROOMSWhereUniqueInput
}

/**
 * SOCK_ROOMS findFirst
 */
export type SOCK_ROOMSFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_ROOMS to fetch.
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_ROOMS to fetch.
   */
  orderBy?: Prisma.SOCK_ROOMSOrderByWithRelationInput | Prisma.SOCK_ROOMSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_ROOMS.
   */
  cursor?: Prisma.SOCK_ROOMSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_ROOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_ROOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_ROOMS.
   */
  distinct?: Prisma.SOCK_ROOMSScalarFieldEnum | Prisma.SOCK_ROOMSScalarFieldEnum[]
}

/**
 * SOCK_ROOMS findFirstOrThrow
 */
export type SOCK_ROOMSFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_ROOMS to fetch.
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_ROOMS to fetch.
   */
  orderBy?: Prisma.SOCK_ROOMSOrderByWithRelationInput | Prisma.SOCK_ROOMSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_ROOMS.
   */
  cursor?: Prisma.SOCK_ROOMSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_ROOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_ROOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_ROOMS.
   */
  distinct?: Prisma.SOCK_ROOMSScalarFieldEnum | Prisma.SOCK_ROOMSScalarFieldEnum[]
}

/**
 * SOCK_ROOMS findMany
 */
export type SOCK_ROOMSFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_ROOMS to fetch.
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_ROOMS to fetch.
   */
  orderBy?: Prisma.SOCK_ROOMSOrderByWithRelationInput | Prisma.SOCK_ROOMSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SOCK_ROOMS.
   */
  cursor?: Prisma.SOCK_ROOMSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_ROOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_ROOMS.
   */
  skip?: number
  distinct?: Prisma.SOCK_ROOMSScalarFieldEnum | Prisma.SOCK_ROOMSScalarFieldEnum[]
}

/**
 * SOCK_ROOMS create
 */
export type SOCK_ROOMSCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * The data needed to create a SOCK_ROOMS.
   */
  data: Prisma.XOR<Prisma.SOCK_ROOMSCreateInput, Prisma.SOCK_ROOMSUncheckedCreateInput>
}

/**
 * SOCK_ROOMS createMany
 */
export type SOCK_ROOMSCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SOCK_ROOMS.
   */
  data: Prisma.SOCK_ROOMSCreateManyInput | Prisma.SOCK_ROOMSCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_ROOMS createManyAndReturn
 */
export type SOCK_ROOMSCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * The data used to create many SOCK_ROOMS.
   */
  data: Prisma.SOCK_ROOMSCreateManyInput | Prisma.SOCK_ROOMSCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_ROOMS update
 */
export type SOCK_ROOMSUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * The data needed to update a SOCK_ROOMS.
   */
  data: Prisma.XOR<Prisma.SOCK_ROOMSUpdateInput, Prisma.SOCK_ROOMSUncheckedUpdateInput>
  /**
   * Choose, which SOCK_ROOMS to update.
   */
  where: Prisma.SOCK_ROOMSWhereUniqueInput
}

/**
 * SOCK_ROOMS updateMany
 */
export type SOCK_ROOMSUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SOCK_ROOMS.
   */
  data: Prisma.XOR<Prisma.SOCK_ROOMSUpdateManyMutationInput, Prisma.SOCK_ROOMSUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_ROOMS to update
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * Limit how many SOCK_ROOMS to update.
   */
  limit?: number
}

/**
 * SOCK_ROOMS updateManyAndReturn
 */
export type SOCK_ROOMSUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * The data used to update SOCK_ROOMS.
   */
  data: Prisma.XOR<Prisma.SOCK_ROOMSUpdateManyMutationInput, Prisma.SOCK_ROOMSUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_ROOMS to update
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * Limit how many SOCK_ROOMS to update.
   */
  limit?: number
}

/**
 * SOCK_ROOMS upsert
 */
export type SOCK_ROOMSUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * The filter to search for the SOCK_ROOMS to update in case it exists.
   */
  where: Prisma.SOCK_ROOMSWhereUniqueInput
  /**
   * In case the SOCK_ROOMS found by the `where` argument doesn't exist, create a new SOCK_ROOMS with this data.
   */
  create: Prisma.XOR<Prisma.SOCK_ROOMSCreateInput, Prisma.SOCK_ROOMSUncheckedCreateInput>
  /**
   * In case the SOCK_ROOMS was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SOCK_ROOMSUpdateInput, Prisma.SOCK_ROOMSUncheckedUpdateInput>
}

/**
 * SOCK_ROOMS delete
 */
export type SOCK_ROOMSDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
  /**
   * Filter which SOCK_ROOMS to delete.
   */
  where: Prisma.SOCK_ROOMSWhereUniqueInput
}

/**
 * SOCK_ROOMS deleteMany
 */
export type SOCK_ROOMSDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_ROOMS to delete
   */
  where?: Prisma.SOCK_ROOMSWhereInput
  /**
   * Limit how many SOCK_ROOMS to delete.
   */
  limit?: number
}

/**
 * SOCK_ROOMS without action
 */
export type SOCK_ROOMSDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_ROOMS
   */
  select?: Prisma.SOCK_ROOMSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_ROOMS
   */
  omit?: Prisma.SOCK_ROOMSOmit<ExtArgs> | null
}
