
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SOCK_USERS` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SOCK_USERS
 * 
 */
export type SOCK_USERSModel = runtime.Types.Result.DefaultSelection<Prisma.$SOCK_USERSPayload>

export type AggregateSOCK_USERS = {
  _count: SOCK_USERSCountAggregateOutputType | null
  _avg: SOCK_USERSAvgAggregateOutputType | null
  _sum: SOCK_USERSSumAggregateOutputType | null
  _min: SOCK_USERSMinAggregateOutputType | null
  _max: SOCK_USERSMaxAggregateOutputType | null
}

export type SOCK_USERSAvgAggregateOutputType = {
  id: number | null
  rooms: number | null
  pending: number | null
  accepted: number | null
}

export type SOCK_USERSSumAggregateOutputType = {
  id: number | null
  rooms: number[]
  pending: number[]
  accepted: number[]
}

export type SOCK_USERSMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  password: string | null
  token: string | null
}

export type SOCK_USERSMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  password: string | null
  token: string | null
}

export type SOCK_USERSCountAggregateOutputType = {
  id: number
  name: number
  email: number
  password: number
  token: number
  rooms: number
  pending: number
  accepted: number
  _all: number
}


export type SOCK_USERSAvgAggregateInputType = {
  id?: true
  rooms?: true
  pending?: true
  accepted?: true
}

export type SOCK_USERSSumAggregateInputType = {
  id?: true
  rooms?: true
  pending?: true
  accepted?: true
}

export type SOCK_USERSMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
}

export type SOCK_USERSMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
}

export type SOCK_USERSCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  token?: true
  rooms?: true
  pending?: true
  accepted?: true
  _all?: true
}

export type SOCK_USERSAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_USERS to aggregate.
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_USERS to fetch.
   */
  orderBy?: Prisma.SOCK_USERSOrderByWithRelationInput | Prisma.SOCK_USERSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SOCK_USERSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_USERS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_USERS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SOCK_USERS
  **/
  _count?: true | SOCK_USERSCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SOCK_USERSAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SOCK_USERSSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SOCK_USERSMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SOCK_USERSMaxAggregateInputType
}

export type GetSOCK_USERSAggregateType<T extends SOCK_USERSAggregateArgs> = {
      [P in keyof T & keyof AggregateSOCK_USERS]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSOCK_USERS[P]>
    : Prisma.GetScalarType<T[P], AggregateSOCK_USERS[P]>
}




export type SOCK_USERSGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SOCK_USERSWhereInput
  orderBy?: Prisma.SOCK_USERSOrderByWithAggregationInput | Prisma.SOCK_USERSOrderByWithAggregationInput[]
  by: Prisma.SOCK_USERSScalarFieldEnum[] | Prisma.SOCK_USERSScalarFieldEnum
  having?: Prisma.SOCK_USERSScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SOCK_USERSCountAggregateInputType | true
  _avg?: SOCK_USERSAvgAggregateInputType
  _sum?: SOCK_USERSSumAggregateInputType
  _min?: SOCK_USERSMinAggregateInputType
  _max?: SOCK_USERSMaxAggregateInputType
}

export type SOCK_USERSGroupByOutputType = {
  id: number
  name: string
  email: string
  password: string
  token: string | null
  rooms: number[]
  pending: number[]
  accepted: number[]
  _count: SOCK_USERSCountAggregateOutputType | null
  _avg: SOCK_USERSAvgAggregateOutputType | null
  _sum: SOCK_USERSSumAggregateOutputType | null
  _min: SOCK_USERSMinAggregateOutputType | null
  _max: SOCK_USERSMaxAggregateOutputType | null
}

type GetSOCK_USERSGroupByPayload<T extends SOCK_USERSGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SOCK_USERSGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SOCK_USERSGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SOCK_USERSGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SOCK_USERSGroupByOutputType[P]>
      }
    >
  >



export type SOCK_USERSWhereInput = {
  AND?: Prisma.SOCK_USERSWhereInput | Prisma.SOCK_USERSWhereInput[]
  OR?: Prisma.SOCK_USERSWhereInput[]
  NOT?: Prisma.SOCK_USERSWhereInput | Prisma.SOCK_USERSWhereInput[]
  id?: Prisma.IntFilter<"SOCK_USERS"> | number
  name?: Prisma.StringFilter<"SOCK_USERS"> | string
  email?: Prisma.StringFilter<"SOCK_USERS"> | string
  password?: Prisma.StringFilter<"SOCK_USERS"> | string
  token?: Prisma.StringNullableFilter<"SOCK_USERS"> | string | null
  rooms?: Prisma.IntNullableListFilter<"SOCK_USERS">
  pending?: Prisma.IntNullableListFilter<"SOCK_USERS">
  accepted?: Prisma.IntNullableListFilter<"SOCK_USERS">
}

export type SOCK_USERSOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  rooms?: Prisma.SortOrder
  pending?: Prisma.SortOrder
  accepted?: Prisma.SortOrder
}

export type SOCK_USERSWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.SOCK_USERSWhereInput | Prisma.SOCK_USERSWhereInput[]
  OR?: Prisma.SOCK_USERSWhereInput[]
  NOT?: Prisma.SOCK_USERSWhereInput | Prisma.SOCK_USERSWhereInput[]
  name?: Prisma.StringFilter<"SOCK_USERS"> | string
  password?: Prisma.StringFilter<"SOCK_USERS"> | string
  token?: Prisma.StringNullableFilter<"SOCK_USERS"> | string | null
  rooms?: Prisma.IntNullableListFilter<"SOCK_USERS">
  pending?: Prisma.IntNullableListFilter<"SOCK_USERS">
  accepted?: Prisma.IntNullableListFilter<"SOCK_USERS">
}, "id" | "email">

export type SOCK_USERSOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  rooms?: Prisma.SortOrder
  pending?: Prisma.SortOrder
  accepted?: Prisma.SortOrder
  _count?: Prisma.SOCK_USERSCountOrderByAggregateInput
  _avg?: Prisma.SOCK_USERSAvgOrderByAggregateInput
  _max?: Prisma.SOCK_USERSMaxOrderByAggregateInput
  _min?: Prisma.SOCK_USERSMinOrderByAggregateInput
  _sum?: Prisma.SOCK_USERSSumOrderByAggregateInput
}

export type SOCK_USERSScalarWhereWithAggregatesInput = {
  AND?: Prisma.SOCK_USERSScalarWhereWithAggregatesInput | Prisma.SOCK_USERSScalarWhereWithAggregatesInput[]
  OR?: Prisma.SOCK_USERSScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SOCK_USERSScalarWhereWithAggregatesInput | Prisma.SOCK_USERSScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SOCK_USERS"> | number
  name?: Prisma.StringWithAggregatesFilter<"SOCK_USERS"> | string
  email?: Prisma.StringWithAggregatesFilter<"SOCK_USERS"> | string
  password?: Prisma.StringWithAggregatesFilter<"SOCK_USERS"> | string
  token?: Prisma.StringNullableWithAggregatesFilter<"SOCK_USERS"> | string | null
  rooms?: Prisma.IntNullableListFilter<"SOCK_USERS">
  pending?: Prisma.IntNullableListFilter<"SOCK_USERS">
  accepted?: Prisma.IntNullableListFilter<"SOCK_USERS">
}

export type SOCK_USERSCreateInput = {
  name: string
  email: string
  password: string
  token?: string | null
  rooms?: Prisma.SOCK_USERSCreateroomsInput | number[]
  pending?: Prisma.SOCK_USERSCreatependingInput | number[]
  accepted?: Prisma.SOCK_USERSCreateacceptedInput | number[]
}

export type SOCK_USERSUncheckedCreateInput = {
  id?: number
  name: string
  email: string
  password: string
  token?: string | null
  rooms?: Prisma.SOCK_USERSCreateroomsInput | number[]
  pending?: Prisma.SOCK_USERSCreatependingInput | number[]
  accepted?: Prisma.SOCK_USERSCreateacceptedInput | number[]
}

export type SOCK_USERSUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rooms?: Prisma.SOCK_USERSUpdateroomsInput | number[]
  pending?: Prisma.SOCK_USERSUpdatependingInput | number[]
  accepted?: Prisma.SOCK_USERSUpdateacceptedInput | number[]
}

export type SOCK_USERSUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rooms?: Prisma.SOCK_USERSUpdateroomsInput | number[]
  pending?: Prisma.SOCK_USERSUpdatependingInput | number[]
  accepted?: Prisma.SOCK_USERSUpdateacceptedInput | number[]
}

export type SOCK_USERSCreateManyInput = {
  id?: number
  name: string
  email: string
  password: string
  token?: string | null
  rooms?: Prisma.SOCK_USERSCreateroomsInput | number[]
  pending?: Prisma.SOCK_USERSCreatependingInput | number[]
  accepted?: Prisma.SOCK_USERSCreateacceptedInput | number[]
}

export type SOCK_USERSUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rooms?: Prisma.SOCK_USERSUpdateroomsInput | number[]
  pending?: Prisma.SOCK_USERSUpdatependingInput | number[]
  accepted?: Prisma.SOCK_USERSUpdateacceptedInput | number[]
}

export type SOCK_USERSUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rooms?: Prisma.SOCK_USERSUpdateroomsInput | number[]
  pending?: Prisma.SOCK_USERSUpdatependingInput | number[]
  accepted?: Prisma.SOCK_USERSUpdateacceptedInput | number[]
}

export type IntNullableListFilter<$PrismaModel = never> = {
  equals?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  has?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  hasEvery?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  hasSome?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type SOCK_USERSCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  pending?: Prisma.SortOrder
  accepted?: Prisma.SortOrder
}

export type SOCK_USERSAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  pending?: Prisma.SortOrder
  accepted?: Prisma.SortOrder
}

export type SOCK_USERSMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type SOCK_USERSMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type SOCK_USERSSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rooms?: Prisma.SortOrder
  pending?: Prisma.SortOrder
  accepted?: Prisma.SortOrder
}

export type SOCK_USERSCreateroomsInput = {
  set: number[]
}

export type SOCK_USERSCreatependingInput = {
  set: number[]
}

export type SOCK_USERSCreateacceptedInput = {
  set: number[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type SOCK_USERSUpdateroomsInput = {
  set?: number[]
  push?: number | number[]
}

export type SOCK_USERSUpdatependingInput = {
  set?: number[]
  push?: number | number[]
}

export type SOCK_USERSUpdateacceptedInput = {
  set?: number[]
  push?: number | number[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type SOCK_USERSSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  pending?: boolean
  accepted?: boolean
}, ExtArgs["result"]["sOCK_USERS"]>

export type SOCK_USERSSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  pending?: boolean
  accepted?: boolean
}, ExtArgs["result"]["sOCK_USERS"]>

export type SOCK_USERSSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  pending?: boolean
  accepted?: boolean
}, ExtArgs["result"]["sOCK_USERS"]>

export type SOCK_USERSSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  token?: boolean
  rooms?: boolean
  pending?: boolean
  accepted?: boolean
}

export type SOCK_USERSOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "password" | "token" | "rooms" | "pending" | "accepted", ExtArgs["result"]["sOCK_USERS"]>

export type $SOCK_USERSPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SOCK_USERS"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    email: string
    password: string
    token: string | null
    rooms: number[]
    pending: number[]
    accepted: number[]
  }, ExtArgs["result"]["sOCK_USERS"]>
  composites: {}
}

export type SOCK_USERSGetPayload<S extends boolean | null | undefined | SOCK_USERSDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload, S>

export type SOCK_USERSCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SOCK_USERSFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SOCK_USERSCountAggregateInputType | true
  }

export interface SOCK_USERSDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SOCK_USERS'], meta: { name: 'SOCK_USERS' } }
  /**
   * Find zero or one SOCK_USERS that matches the filter.
   * @param {SOCK_USERSFindUniqueArgs} args - Arguments to find a SOCK_USERS
   * @example
   * // Get one SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SOCK_USERSFindUniqueArgs>(args: Prisma.SelectSubset<T, SOCK_USERSFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SOCK_USERS that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SOCK_USERSFindUniqueOrThrowArgs} args - Arguments to find a SOCK_USERS
   * @example
   * // Get one SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SOCK_USERSFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SOCK_USERSFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_USERS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSFindFirstArgs} args - Arguments to find a SOCK_USERS
   * @example
   * // Get one SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SOCK_USERSFindFirstArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSFindFirstArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_USERS that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSFindFirstOrThrowArgs} args - Arguments to find a SOCK_USERS
   * @example
   * // Get one SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SOCK_USERSFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SOCK_USERS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findMany()
   * 
   * // Get first 10 SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sOCK_USERSWithIdOnly = await prisma.sOCK_USERS.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SOCK_USERSFindManyArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SOCK_USERS.
   * @param {SOCK_USERSCreateArgs} args - Arguments to create a SOCK_USERS.
   * @example
   * // Create one SOCK_USERS
   * const SOCK_USERS = await prisma.sOCK_USERS.create({
   *   data: {
   *     // ... data to create a SOCK_USERS
   *   }
   * })
   * 
   */
  create<T extends SOCK_USERSCreateArgs>(args: Prisma.SelectSubset<T, SOCK_USERSCreateArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SOCK_USERS.
   * @param {SOCK_USERSCreateManyArgs} args - Arguments to create many SOCK_USERS.
   * @example
   * // Create many SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SOCK_USERSCreateManyArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SOCK_USERS and returns the data saved in the database.
   * @param {SOCK_USERSCreateManyAndReturnArgs} args - Arguments to create many SOCK_USERS.
   * @example
   * // Create many SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SOCK_USERS and only return the `id`
   * const sOCK_USERSWithIdOnly = await prisma.sOCK_USERS.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SOCK_USERSCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SOCK_USERS.
   * @param {SOCK_USERSDeleteArgs} args - Arguments to delete one SOCK_USERS.
   * @example
   * // Delete one SOCK_USERS
   * const SOCK_USERS = await prisma.sOCK_USERS.delete({
   *   where: {
   *     // ... filter to delete one SOCK_USERS
   *   }
   * })
   * 
   */
  delete<T extends SOCK_USERSDeleteArgs>(args: Prisma.SelectSubset<T, SOCK_USERSDeleteArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SOCK_USERS.
   * @param {SOCK_USERSUpdateArgs} args - Arguments to update one SOCK_USERS.
   * @example
   * // Update one SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SOCK_USERSUpdateArgs>(args: Prisma.SelectSubset<T, SOCK_USERSUpdateArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SOCK_USERS.
   * @param {SOCK_USERSDeleteManyArgs} args - Arguments to filter SOCK_USERS to delete.
   * @example
   * // Delete a few SOCK_USERS
   * const { count } = await prisma.sOCK_USERS.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SOCK_USERSDeleteManyArgs>(args?: Prisma.SelectSubset<T, SOCK_USERSDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_USERS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SOCK_USERSUpdateManyArgs>(args: Prisma.SelectSubset<T, SOCK_USERSUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_USERS and returns the data updated in the database.
   * @param {SOCK_USERSUpdateManyAndReturnArgs} args - Arguments to update many SOCK_USERS.
   * @example
   * // Update many SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SOCK_USERS and only return the `id`
   * const sOCK_USERSWithIdOnly = await prisma.sOCK_USERS.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SOCK_USERSUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SOCK_USERSUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SOCK_USERS.
   * @param {SOCK_USERSUpsertArgs} args - Arguments to update or create a SOCK_USERS.
   * @example
   * // Update or create a SOCK_USERS
   * const sOCK_USERS = await prisma.sOCK_USERS.upsert({
   *   create: {
   *     // ... data to create a SOCK_USERS
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SOCK_USERS we want to update
   *   }
   * })
   */
  upsert<T extends SOCK_USERSUpsertArgs>(args: Prisma.SelectSubset<T, SOCK_USERSUpsertArgs<ExtArgs>>): Prisma.Prisma__SOCK_USERSClient<runtime.Types.Result.GetResult<Prisma.$SOCK_USERSPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SOCK_USERS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSCountArgs} args - Arguments to filter SOCK_USERS to count.
   * @example
   * // Count the number of SOCK_USERS
   * const count = await prisma.sOCK_USERS.count({
   *   where: {
   *     // ... the filter for the SOCK_USERS we want to count
   *   }
   * })
  **/
  count<T extends SOCK_USERSCountArgs>(
    args?: Prisma.Subset<T, SOCK_USERSCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SOCK_USERSCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SOCK_USERS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SOCK_USERSAggregateArgs>(args: Prisma.Subset<T, SOCK_USERSAggregateArgs>): Prisma.PrismaPromise<GetSOCK_USERSAggregateType<T>>

  /**
   * Group by SOCK_USERS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_USERSGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SOCK_USERSGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SOCK_USERSGroupByArgs['orderBy'] }
      : { orderBy?: SOCK_USERSGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SOCK_USERSGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSOCK_USERSGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SOCK_USERS model
 */
readonly fields: SOCK_USERSFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SOCK_USERS.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SOCK_USERSClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SOCK_USERS model
 */
export interface SOCK_USERSFieldRefs {
  readonly id: Prisma.FieldRef<"SOCK_USERS", 'Int'>
  readonly name: Prisma.FieldRef<"SOCK_USERS", 'String'>
  readonly email: Prisma.FieldRef<"SOCK_USERS", 'String'>
  readonly password: Prisma.FieldRef<"SOCK_USERS", 'String'>
  readonly token: Prisma.FieldRef<"SOCK_USERS", 'String'>
  readonly rooms: Prisma.FieldRef<"SOCK_USERS", 'Int[]'>
  readonly pending: Prisma.FieldRef<"SOCK_USERS", 'Int[]'>
  readonly accepted: Prisma.FieldRef<"SOCK_USERS", 'Int[]'>
}
    

// Custom InputTypes
/**
 * SOCK_USERS findUnique
 */
export type SOCK_USERSFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_USERS to fetch.
   */
  where: Prisma.SOCK_USERSWhereUniqueInput
}

/**
 * SOCK_USERS findUniqueOrThrow
 */
export type SOCK_USERSFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_USERS to fetch.
   */
  where: Prisma.SOCK_USERSWhereUniqueInput
}

/**
 * SOCK_USERS findFirst
 */
export type SOCK_USERSFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_USERS to fetch.
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_USERS to fetch.
   */
  orderBy?: Prisma.SOCK_USERSOrderByWithRelationInput | Prisma.SOCK_USERSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_USERS.
   */
  cursor?: Prisma.SOCK_USERSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_USERS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_USERS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_USERS.
   */
  distinct?: Prisma.SOCK_USERSScalarFieldEnum | Prisma.SOCK_USERSScalarFieldEnum[]
}

/**
 * SOCK_USERS findFirstOrThrow
 */
export type SOCK_USERSFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_USERS to fetch.
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_USERS to fetch.
   */
  orderBy?: Prisma.SOCK_USERSOrderByWithRelationInput | Prisma.SOCK_USERSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_USERS.
   */
  cursor?: Prisma.SOCK_USERSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_USERS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_USERS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_USERS.
   */
  distinct?: Prisma.SOCK_USERSScalarFieldEnum | Prisma.SOCK_USERSScalarFieldEnum[]
}

/**
 * SOCK_USERS findMany
 */
export type SOCK_USERSFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_USERS to fetch.
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_USERS to fetch.
   */
  orderBy?: Prisma.SOCK_USERSOrderByWithRelationInput | Prisma.SOCK_USERSOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SOCK_USERS.
   */
  cursor?: Prisma.SOCK_USERSWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_USERS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_USERS.
   */
  skip?: number
  distinct?: Prisma.SOCK_USERSScalarFieldEnum | Prisma.SOCK_USERSScalarFieldEnum[]
}

/**
 * SOCK_USERS create
 */
export type SOCK_USERSCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * The data needed to create a SOCK_USERS.
   */
  data: Prisma.XOR<Prisma.SOCK_USERSCreateInput, Prisma.SOCK_USERSUncheckedCreateInput>
}

/**
 * SOCK_USERS createMany
 */
export type SOCK_USERSCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SOCK_USERS.
   */
  data: Prisma.SOCK_USERSCreateManyInput | Prisma.SOCK_USERSCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_USERS createManyAndReturn
 */
export type SOCK_USERSCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * The data used to create many SOCK_USERS.
   */
  data: Prisma.SOCK_USERSCreateManyInput | Prisma.SOCK_USERSCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_USERS update
 */
export type SOCK_USERSUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * The data needed to update a SOCK_USERS.
   */
  data: Prisma.XOR<Prisma.SOCK_USERSUpdateInput, Prisma.SOCK_USERSUncheckedUpdateInput>
  /**
   * Choose, which SOCK_USERS to update.
   */
  where: Prisma.SOCK_USERSWhereUniqueInput
}

/**
 * SOCK_USERS updateMany
 */
export type SOCK_USERSUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SOCK_USERS.
   */
  data: Prisma.XOR<Prisma.SOCK_USERSUpdateManyMutationInput, Prisma.SOCK_USERSUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_USERS to update
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * Limit how many SOCK_USERS to update.
   */
  limit?: number
}

/**
 * SOCK_USERS updateManyAndReturn
 */
export type SOCK_USERSUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * The data used to update SOCK_USERS.
   */
  data: Prisma.XOR<Prisma.SOCK_USERSUpdateManyMutationInput, Prisma.SOCK_USERSUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_USERS to update
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * Limit how many SOCK_USERS to update.
   */
  limit?: number
}

/**
 * SOCK_USERS upsert
 */
export type SOCK_USERSUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * The filter to search for the SOCK_USERS to update in case it exists.
   */
  where: Prisma.SOCK_USERSWhereUniqueInput
  /**
   * In case the SOCK_USERS found by the `where` argument doesn't exist, create a new SOCK_USERS with this data.
   */
  create: Prisma.XOR<Prisma.SOCK_USERSCreateInput, Prisma.SOCK_USERSUncheckedCreateInput>
  /**
   * In case the SOCK_USERS was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SOCK_USERSUpdateInput, Prisma.SOCK_USERSUncheckedUpdateInput>
}

/**
 * SOCK_USERS delete
 */
export type SOCK_USERSDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
  /**
   * Filter which SOCK_USERS to delete.
   */
  where: Prisma.SOCK_USERSWhereUniqueInput
}

/**
 * SOCK_USERS deleteMany
 */
export type SOCK_USERSDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_USERS to delete
   */
  where?: Prisma.SOCK_USERSWhereInput
  /**
   * Limit how many SOCK_USERS to delete.
   */
  limit?: number
}

/**
 * SOCK_USERS without action
 */
export type SOCK_USERSDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_USERS
   */
  select?: Prisma.SOCK_USERSSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_USERS
   */
  omit?: Prisma.SOCK_USERSOmit<ExtArgs> | null
}
