
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SOCK_PAYLOAD` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SOCK_PAYLOAD
 * 
 */
export type SOCK_PAYLOADModel = runtime.Types.Result.DefaultSelection<Prisma.$SOCK_PAYLOADPayload>

export type AggregateSOCK_PAYLOAD = {
  _count: SOCK_PAYLOADCountAggregateOutputType | null
  _avg: SOCK_PAYLOADAvgAggregateOutputType | null
  _sum: SOCK_PAYLOADSumAggregateOutputType | null
  _min: SOCK_PAYLOADMinAggregateOutputType | null
  _max: SOCK_PAYLOADMaxAggregateOutputType | null
}

export type SOCK_PAYLOADAvgAggregateOutputType = {
  id: number | null
  room_id: number | null
  sender: number | null
}

export type SOCK_PAYLOADSumAggregateOutputType = {
  id: number | null
  room_id: number | null
  sender: number | null
}

export type SOCK_PAYLOADMinAggregateOutputType = {
  id: number | null
  room_id: number | null
  sender: number | null
  payload: string | null
  created_at: Date | null
}

export type SOCK_PAYLOADMaxAggregateOutputType = {
  id: number | null
  room_id: number | null
  sender: number | null
  payload: string | null
  created_at: Date | null
}

export type SOCK_PAYLOADCountAggregateOutputType = {
  id: number
  room_id: number
  sender: number
  payload: number
  created_at: number
  _all: number
}


export type SOCK_PAYLOADAvgAggregateInputType = {
  id?: true
  room_id?: true
  sender?: true
}

export type SOCK_PAYLOADSumAggregateInputType = {
  id?: true
  room_id?: true
  sender?: true
}

export type SOCK_PAYLOADMinAggregateInputType = {
  id?: true
  room_id?: true
  sender?: true
  payload?: true
  created_at?: true
}

export type SOCK_PAYLOADMaxAggregateInputType = {
  id?: true
  room_id?: true
  sender?: true
  payload?: true
  created_at?: true
}

export type SOCK_PAYLOADCountAggregateInputType = {
  id?: true
  room_id?: true
  sender?: true
  payload?: true
  created_at?: true
  _all?: true
}

export type SOCK_PAYLOADAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_PAYLOAD to aggregate.
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_PAYLOADS to fetch.
   */
  orderBy?: Prisma.SOCK_PAYLOADOrderByWithRelationInput | Prisma.SOCK_PAYLOADOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SOCK_PAYLOADWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_PAYLOADS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_PAYLOADS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SOCK_PAYLOADS
  **/
  _count?: true | SOCK_PAYLOADCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SOCK_PAYLOADAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SOCK_PAYLOADSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SOCK_PAYLOADMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SOCK_PAYLOADMaxAggregateInputType
}

export type GetSOCK_PAYLOADAggregateType<T extends SOCK_PAYLOADAggregateArgs> = {
      [P in keyof T & keyof AggregateSOCK_PAYLOAD]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSOCK_PAYLOAD[P]>
    : Prisma.GetScalarType<T[P], AggregateSOCK_PAYLOAD[P]>
}




export type SOCK_PAYLOADGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SOCK_PAYLOADWhereInput
  orderBy?: Prisma.SOCK_PAYLOADOrderByWithAggregationInput | Prisma.SOCK_PAYLOADOrderByWithAggregationInput[]
  by: Prisma.SOCK_PAYLOADScalarFieldEnum[] | Prisma.SOCK_PAYLOADScalarFieldEnum
  having?: Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SOCK_PAYLOADCountAggregateInputType | true
  _avg?: SOCK_PAYLOADAvgAggregateInputType
  _sum?: SOCK_PAYLOADSumAggregateInputType
  _min?: SOCK_PAYLOADMinAggregateInputType
  _max?: SOCK_PAYLOADMaxAggregateInputType
}

export type SOCK_PAYLOADGroupByOutputType = {
  id: number
  room_id: number
  sender: number
  payload: string
  created_at: Date
  _count: SOCK_PAYLOADCountAggregateOutputType | null
  _avg: SOCK_PAYLOADAvgAggregateOutputType | null
  _sum: SOCK_PAYLOADSumAggregateOutputType | null
  _min: SOCK_PAYLOADMinAggregateOutputType | null
  _max: SOCK_PAYLOADMaxAggregateOutputType | null
}

type GetSOCK_PAYLOADGroupByPayload<T extends SOCK_PAYLOADGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SOCK_PAYLOADGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SOCK_PAYLOADGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SOCK_PAYLOADGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SOCK_PAYLOADGroupByOutputType[P]>
      }
    >
  >



export type SOCK_PAYLOADWhereInput = {
  AND?: Prisma.SOCK_PAYLOADWhereInput | Prisma.SOCK_PAYLOADWhereInput[]
  OR?: Prisma.SOCK_PAYLOADWhereInput[]
  NOT?: Prisma.SOCK_PAYLOADWhereInput | Prisma.SOCK_PAYLOADWhereInput[]
  id?: Prisma.IntFilter<"SOCK_PAYLOAD"> | number
  room_id?: Prisma.IntFilter<"SOCK_PAYLOAD"> | number
  sender?: Prisma.IntFilter<"SOCK_PAYLOAD"> | number
  payload?: Prisma.StringFilter<"SOCK_PAYLOAD"> | string
  created_at?: Prisma.DateTimeFilter<"SOCK_PAYLOAD"> | Date | string
}

export type SOCK_PAYLOADOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SOCK_PAYLOADWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SOCK_PAYLOADWhereInput | Prisma.SOCK_PAYLOADWhereInput[]
  OR?: Prisma.SOCK_PAYLOADWhereInput[]
  NOT?: Prisma.SOCK_PAYLOADWhereInput | Prisma.SOCK_PAYLOADWhereInput[]
  room_id?: Prisma.IntFilter<"SOCK_PAYLOAD"> | number
  sender?: Prisma.IntFilter<"SOCK_PAYLOAD"> | number
  payload?: Prisma.StringFilter<"SOCK_PAYLOAD"> | string
  created_at?: Prisma.DateTimeFilter<"SOCK_PAYLOAD"> | Date | string
}, "id">

export type SOCK_PAYLOADOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.SOCK_PAYLOADCountOrderByAggregateInput
  _avg?: Prisma.SOCK_PAYLOADAvgOrderByAggregateInput
  _max?: Prisma.SOCK_PAYLOADMaxOrderByAggregateInput
  _min?: Prisma.SOCK_PAYLOADMinOrderByAggregateInput
  _sum?: Prisma.SOCK_PAYLOADSumOrderByAggregateInput
}

export type SOCK_PAYLOADScalarWhereWithAggregatesInput = {
  AND?: Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput | Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput[]
  OR?: Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput | Prisma.SOCK_PAYLOADScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SOCK_PAYLOAD"> | number
  room_id?: Prisma.IntWithAggregatesFilter<"SOCK_PAYLOAD"> | number
  sender?: Prisma.IntWithAggregatesFilter<"SOCK_PAYLOAD"> | number
  payload?: Prisma.StringWithAggregatesFilter<"SOCK_PAYLOAD"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"SOCK_PAYLOAD"> | Date | string
}

export type SOCK_PAYLOADCreateInput = {
  room_id: number
  sender: number
  payload: string
  created_at?: Date | string
}

export type SOCK_PAYLOADUncheckedCreateInput = {
  id?: number
  room_id: number
  sender: number
  payload: string
  created_at?: Date | string
}

export type SOCK_PAYLOADUpdateInput = {
  room_id?: Prisma.IntFieldUpdateOperationsInput | number
  sender?: Prisma.IntFieldUpdateOperationsInput | number
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SOCK_PAYLOADUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  room_id?: Prisma.IntFieldUpdateOperationsInput | number
  sender?: Prisma.IntFieldUpdateOperationsInput | number
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SOCK_PAYLOADCreateManyInput = {
  id?: number
  room_id: number
  sender: number
  payload: string
  created_at?: Date | string
}

export type SOCK_PAYLOADUpdateManyMutationInput = {
  room_id?: Prisma.IntFieldUpdateOperationsInput | number
  sender?: Prisma.IntFieldUpdateOperationsInput | number
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SOCK_PAYLOADUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  room_id?: Prisma.IntFieldUpdateOperationsInput | number
  sender?: Prisma.IntFieldUpdateOperationsInput | number
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SOCK_PAYLOADCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SOCK_PAYLOADAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
}

export type SOCK_PAYLOADMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SOCK_PAYLOADMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type SOCK_PAYLOADSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  room_id?: Prisma.SortOrder
  sender?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type SOCK_PAYLOADSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  room_id?: boolean
  sender?: boolean
  payload?: boolean
  created_at?: boolean
}, ExtArgs["result"]["sOCK_PAYLOAD"]>

export type SOCK_PAYLOADSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  room_id?: boolean
  sender?: boolean
  payload?: boolean
  created_at?: boolean
}, ExtArgs["result"]["sOCK_PAYLOAD"]>

export type SOCK_PAYLOADSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  room_id?: boolean
  sender?: boolean
  payload?: boolean
  created_at?: boolean
}, ExtArgs["result"]["sOCK_PAYLOAD"]>

export type SOCK_PAYLOADSelectScalar = {
  id?: boolean
  room_id?: boolean
  sender?: boolean
  payload?: boolean
  created_at?: boolean
}

export type SOCK_PAYLOADOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "room_id" | "sender" | "payload" | "created_at", ExtArgs["result"]["sOCK_PAYLOAD"]>

export type $SOCK_PAYLOADPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SOCK_PAYLOAD"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    room_id: number
    sender: number
    payload: string
    created_at: Date
  }, ExtArgs["result"]["sOCK_PAYLOAD"]>
  composites: {}
}

export type SOCK_PAYLOADGetPayload<S extends boolean | null | undefined | SOCK_PAYLOADDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload, S>

export type SOCK_PAYLOADCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SOCK_PAYLOADFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SOCK_PAYLOADCountAggregateInputType | true
  }

export interface SOCK_PAYLOADDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SOCK_PAYLOAD'], meta: { name: 'SOCK_PAYLOAD' } }
  /**
   * Find zero or one SOCK_PAYLOAD that matches the filter.
   * @param {SOCK_PAYLOADFindUniqueArgs} args - Arguments to find a SOCK_PAYLOAD
   * @example
   * // Get one SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SOCK_PAYLOADFindUniqueArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SOCK_PAYLOAD that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SOCK_PAYLOADFindUniqueOrThrowArgs} args - Arguments to find a SOCK_PAYLOAD
   * @example
   * // Get one SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SOCK_PAYLOADFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_PAYLOAD that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADFindFirstArgs} args - Arguments to find a SOCK_PAYLOAD
   * @example
   * // Get one SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SOCK_PAYLOADFindFirstArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADFindFirstArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SOCK_PAYLOAD that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADFindFirstOrThrowArgs} args - Arguments to find a SOCK_PAYLOAD
   * @example
   * // Get one SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SOCK_PAYLOADFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SOCK_PAYLOADS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SOCK_PAYLOADS
   * const sOCK_PAYLOADS = await prisma.sOCK_PAYLOAD.findMany()
   * 
   * // Get first 10 SOCK_PAYLOADS
   * const sOCK_PAYLOADS = await prisma.sOCK_PAYLOAD.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sOCK_PAYLOADWithIdOnly = await prisma.sOCK_PAYLOAD.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SOCK_PAYLOADFindManyArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SOCK_PAYLOAD.
   * @param {SOCK_PAYLOADCreateArgs} args - Arguments to create a SOCK_PAYLOAD.
   * @example
   * // Create one SOCK_PAYLOAD
   * const SOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.create({
   *   data: {
   *     // ... data to create a SOCK_PAYLOAD
   *   }
   * })
   * 
   */
  create<T extends SOCK_PAYLOADCreateArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADCreateArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SOCK_PAYLOADS.
   * @param {SOCK_PAYLOADCreateManyArgs} args - Arguments to create many SOCK_PAYLOADS.
   * @example
   * // Create many SOCK_PAYLOADS
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SOCK_PAYLOADCreateManyArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SOCK_PAYLOADS and returns the data saved in the database.
   * @param {SOCK_PAYLOADCreateManyAndReturnArgs} args - Arguments to create many SOCK_PAYLOADS.
   * @example
   * // Create many SOCK_PAYLOADS
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SOCK_PAYLOADS and only return the `id`
   * const sOCK_PAYLOADWithIdOnly = await prisma.sOCK_PAYLOAD.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SOCK_PAYLOADCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SOCK_PAYLOAD.
   * @param {SOCK_PAYLOADDeleteArgs} args - Arguments to delete one SOCK_PAYLOAD.
   * @example
   * // Delete one SOCK_PAYLOAD
   * const SOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.delete({
   *   where: {
   *     // ... filter to delete one SOCK_PAYLOAD
   *   }
   * })
   * 
   */
  delete<T extends SOCK_PAYLOADDeleteArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADDeleteArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SOCK_PAYLOAD.
   * @param {SOCK_PAYLOADUpdateArgs} args - Arguments to update one SOCK_PAYLOAD.
   * @example
   * // Update one SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SOCK_PAYLOADUpdateArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADUpdateArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SOCK_PAYLOADS.
   * @param {SOCK_PAYLOADDeleteManyArgs} args - Arguments to filter SOCK_PAYLOADS to delete.
   * @example
   * // Delete a few SOCK_PAYLOADS
   * const { count } = await prisma.sOCK_PAYLOAD.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SOCK_PAYLOADDeleteManyArgs>(args?: Prisma.SelectSubset<T, SOCK_PAYLOADDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_PAYLOADS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SOCK_PAYLOADS
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SOCK_PAYLOADUpdateManyArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SOCK_PAYLOADS and returns the data updated in the database.
   * @param {SOCK_PAYLOADUpdateManyAndReturnArgs} args - Arguments to update many SOCK_PAYLOADS.
   * @example
   * // Update many SOCK_PAYLOADS
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SOCK_PAYLOADS and only return the `id`
   * const sOCK_PAYLOADWithIdOnly = await prisma.sOCK_PAYLOAD.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SOCK_PAYLOADUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SOCK_PAYLOAD.
   * @param {SOCK_PAYLOADUpsertArgs} args - Arguments to update or create a SOCK_PAYLOAD.
   * @example
   * // Update or create a SOCK_PAYLOAD
   * const sOCK_PAYLOAD = await prisma.sOCK_PAYLOAD.upsert({
   *   create: {
   *     // ... data to create a SOCK_PAYLOAD
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SOCK_PAYLOAD we want to update
   *   }
   * })
   */
  upsert<T extends SOCK_PAYLOADUpsertArgs>(args: Prisma.SelectSubset<T, SOCK_PAYLOADUpsertArgs<ExtArgs>>): Prisma.Prisma__SOCK_PAYLOADClient<runtime.Types.Result.GetResult<Prisma.$SOCK_PAYLOADPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SOCK_PAYLOADS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADCountArgs} args - Arguments to filter SOCK_PAYLOADS to count.
   * @example
   * // Count the number of SOCK_PAYLOADS
   * const count = await prisma.sOCK_PAYLOAD.count({
   *   where: {
   *     // ... the filter for the SOCK_PAYLOADS we want to count
   *   }
   * })
  **/
  count<T extends SOCK_PAYLOADCountArgs>(
    args?: Prisma.Subset<T, SOCK_PAYLOADCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SOCK_PAYLOADCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SOCK_PAYLOAD.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SOCK_PAYLOADAggregateArgs>(args: Prisma.Subset<T, SOCK_PAYLOADAggregateArgs>): Prisma.PrismaPromise<GetSOCK_PAYLOADAggregateType<T>>

  /**
   * Group by SOCK_PAYLOAD.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SOCK_PAYLOADGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SOCK_PAYLOADGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SOCK_PAYLOADGroupByArgs['orderBy'] }
      : { orderBy?: SOCK_PAYLOADGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SOCK_PAYLOADGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSOCK_PAYLOADGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SOCK_PAYLOAD model
 */
readonly fields: SOCK_PAYLOADFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SOCK_PAYLOAD.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SOCK_PAYLOADClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SOCK_PAYLOAD model
 */
export interface SOCK_PAYLOADFieldRefs {
  readonly id: Prisma.FieldRef<"SOCK_PAYLOAD", 'Int'>
  readonly room_id: Prisma.FieldRef<"SOCK_PAYLOAD", 'Int'>
  readonly sender: Prisma.FieldRef<"SOCK_PAYLOAD", 'Int'>
  readonly payload: Prisma.FieldRef<"SOCK_PAYLOAD", 'String'>
  readonly created_at: Prisma.FieldRef<"SOCK_PAYLOAD", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SOCK_PAYLOAD findUnique
 */
export type SOCK_PAYLOADFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_PAYLOAD to fetch.
   */
  where: Prisma.SOCK_PAYLOADWhereUniqueInput
}

/**
 * SOCK_PAYLOAD findUniqueOrThrow
 */
export type SOCK_PAYLOADFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_PAYLOAD to fetch.
   */
  where: Prisma.SOCK_PAYLOADWhereUniqueInput
}

/**
 * SOCK_PAYLOAD findFirst
 */
export type SOCK_PAYLOADFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_PAYLOAD to fetch.
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_PAYLOADS to fetch.
   */
  orderBy?: Prisma.SOCK_PAYLOADOrderByWithRelationInput | Prisma.SOCK_PAYLOADOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_PAYLOADS.
   */
  cursor?: Prisma.SOCK_PAYLOADWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_PAYLOADS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_PAYLOADS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_PAYLOADS.
   */
  distinct?: Prisma.SOCK_PAYLOADScalarFieldEnum | Prisma.SOCK_PAYLOADScalarFieldEnum[]
}

/**
 * SOCK_PAYLOAD findFirstOrThrow
 */
export type SOCK_PAYLOADFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_PAYLOAD to fetch.
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_PAYLOADS to fetch.
   */
  orderBy?: Prisma.SOCK_PAYLOADOrderByWithRelationInput | Prisma.SOCK_PAYLOADOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SOCK_PAYLOADS.
   */
  cursor?: Prisma.SOCK_PAYLOADWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_PAYLOADS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_PAYLOADS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SOCK_PAYLOADS.
   */
  distinct?: Prisma.SOCK_PAYLOADScalarFieldEnum | Prisma.SOCK_PAYLOADScalarFieldEnum[]
}

/**
 * SOCK_PAYLOAD findMany
 */
export type SOCK_PAYLOADFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter, which SOCK_PAYLOADS to fetch.
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SOCK_PAYLOADS to fetch.
   */
  orderBy?: Prisma.SOCK_PAYLOADOrderByWithRelationInput | Prisma.SOCK_PAYLOADOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SOCK_PAYLOADS.
   */
  cursor?: Prisma.SOCK_PAYLOADWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SOCK_PAYLOADS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SOCK_PAYLOADS.
   */
  skip?: number
  distinct?: Prisma.SOCK_PAYLOADScalarFieldEnum | Prisma.SOCK_PAYLOADScalarFieldEnum[]
}

/**
 * SOCK_PAYLOAD create
 */
export type SOCK_PAYLOADCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * The data needed to create a SOCK_PAYLOAD.
   */
  data: Prisma.XOR<Prisma.SOCK_PAYLOADCreateInput, Prisma.SOCK_PAYLOADUncheckedCreateInput>
}

/**
 * SOCK_PAYLOAD createMany
 */
export type SOCK_PAYLOADCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SOCK_PAYLOADS.
   */
  data: Prisma.SOCK_PAYLOADCreateManyInput | Prisma.SOCK_PAYLOADCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_PAYLOAD createManyAndReturn
 */
export type SOCK_PAYLOADCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * The data used to create many SOCK_PAYLOADS.
   */
  data: Prisma.SOCK_PAYLOADCreateManyInput | Prisma.SOCK_PAYLOADCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SOCK_PAYLOAD update
 */
export type SOCK_PAYLOADUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * The data needed to update a SOCK_PAYLOAD.
   */
  data: Prisma.XOR<Prisma.SOCK_PAYLOADUpdateInput, Prisma.SOCK_PAYLOADUncheckedUpdateInput>
  /**
   * Choose, which SOCK_PAYLOAD to update.
   */
  where: Prisma.SOCK_PAYLOADWhereUniqueInput
}

/**
 * SOCK_PAYLOAD updateMany
 */
export type SOCK_PAYLOADUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SOCK_PAYLOADS.
   */
  data: Prisma.XOR<Prisma.SOCK_PAYLOADUpdateManyMutationInput, Prisma.SOCK_PAYLOADUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_PAYLOADS to update
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * Limit how many SOCK_PAYLOADS to update.
   */
  limit?: number
}

/**
 * SOCK_PAYLOAD updateManyAndReturn
 */
export type SOCK_PAYLOADUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * The data used to update SOCK_PAYLOADS.
   */
  data: Prisma.XOR<Prisma.SOCK_PAYLOADUpdateManyMutationInput, Prisma.SOCK_PAYLOADUncheckedUpdateManyInput>
  /**
   * Filter which SOCK_PAYLOADS to update
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * Limit how many SOCK_PAYLOADS to update.
   */
  limit?: number
}

/**
 * SOCK_PAYLOAD upsert
 */
export type SOCK_PAYLOADUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * The filter to search for the SOCK_PAYLOAD to update in case it exists.
   */
  where: Prisma.SOCK_PAYLOADWhereUniqueInput
  /**
   * In case the SOCK_PAYLOAD found by the `where` argument doesn't exist, create a new SOCK_PAYLOAD with this data.
   */
  create: Prisma.XOR<Prisma.SOCK_PAYLOADCreateInput, Prisma.SOCK_PAYLOADUncheckedCreateInput>
  /**
   * In case the SOCK_PAYLOAD was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SOCK_PAYLOADUpdateInput, Prisma.SOCK_PAYLOADUncheckedUpdateInput>
}

/**
 * SOCK_PAYLOAD delete
 */
export type SOCK_PAYLOADDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
  /**
   * Filter which SOCK_PAYLOAD to delete.
   */
  where: Prisma.SOCK_PAYLOADWhereUniqueInput
}

/**
 * SOCK_PAYLOAD deleteMany
 */
export type SOCK_PAYLOADDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SOCK_PAYLOADS to delete
   */
  where?: Prisma.SOCK_PAYLOADWhereInput
  /**
   * Limit how many SOCK_PAYLOADS to delete.
   */
  limit?: number
}

/**
 * SOCK_PAYLOAD without action
 */
export type SOCK_PAYLOADDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SOCK_PAYLOAD
   */
  select?: Prisma.SOCK_PAYLOADSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SOCK_PAYLOAD
   */
  omit?: Prisma.SOCK_PAYLOADOmit<ExtArgs> | null
}
